service: hex-auth

custom:
    stage: ${opt:stage, self:provider.stage}

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2
    deploymentBucket:
        name: hex-deployment-bucket
        serverSideEncryption: AES256

#funcitons:
#    postConfirm:
#        handler: postConfirm.main
#        events:
#            - HexUserPool
#                pool: HexUserPool
#                trigger: PostConfirmation

resources:
    Resources:
        # User Pool
        HexUserPool:
            Type: AWS::Cognito::UserPool
            Properties:
                # Pool name based on stage
                UserPoolName: hex-${self:custom.stage}-user-pool

                UsernameAttributes:
                    - email

                AutoVerifiedAttributes:
                    - email

                Schema:
                    - Name: email
                      AttributeDataType: String
                      Mutable: true
                      Required: true

                # Password Policy
                Policies:
                    PasswordPolicy:
                        MinimumLength: 15
                        RequireLowercase: false
                        RequireNumbers: false
                        RequireSymbols: false
                        RequireUppercase: false

        HexWebAppClient:
            Type: AWS::Cognito::UserPoolClient
            Properties:
                # Generate an App Client Name based on stage
                ClientName: hex-${self:custom.stage}-web-app-client
                UserPoolId:
                    Ref: HexUserPool
                GenerateSecret: false


    # Output, mostly for testing purposes
    Outputs:
        HexUserPoolId:
            Value:
                Ref: HexUserPool
            Export:
                Name: ${self:custom.stage}-hex-user-pool-id
        HexUserPoolArn:
            Value:
                Fn::GetAtt:
                    - HexUserPool
                    - Arn
            Export:
                Name: ${self:custom.stage}-hex-user-pool-arn