service: hex-auth

custom:
    stage: ${opt:stage, self:provider.stage}

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2

resources:
    Resources:
        CognitoUserPool:
            Type: AWS::Cognito::UserPool
            Properties:
                # Pool name based on stage
                UserPoolName: hex-${self:custom.stage}-user-pool

                # Set Preferred Username as Alias
                AliasAttributes:
                    - preferred_username

        CognitoUserPoolClient:
            Type: AWS::Cognito::UserPoolClient
            Properties:
                # Generate an App Client Name based on stage
                ClientName: hex-${self:custom.stage}-user-pool-client
                UserPoolId:
                    Ref: CognitoUserPool
                ExplicitAuthFlows:
                    - ADMIN_NO_SRP_AUTH
                GenerateSecret: false
