service: hex-api-users

custom:
    # Our stage is based on what is passed in when running serverless
    # commands. Or falls back to what we have set in the provider section.
    stage: ${opt:stage, self:provider.stage}

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2
    deploymentBucket:
        name: hex-deployment-bucket
        serverSideEncryption: AES256
    apiGateway:
        restApiId:
            'Fn::ImportValue': ${self:custom.stage}-HexApiGateway-restApiId
        restApiRootResourceId:
            'Fn::ImportValue': ${self:custom.stage}-HexApiGateway-rootResourceId

functions:
    users:
        handler: users.main
        events:
            - http:
                path: hello
                method: get
                cors: true
                authorizer:
                    name: CustomAuthorizer
                    arn:
                        Fn::ImportValue: ${self:custom.stage}-authorizer