service: faunadb-custom-resource

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2
    deploymentBucket:
        name: hex-deployment-bucket
        serverSideEncryption: AES256

resources:
    Resources:
        # Our custom resource
        FaunaDB:
            Type: Custom::FaunaClass
            Properties:
                ServiceToken:
                    Fn::ImportValue: fauna-class-lambda-arn
                ClassName: users
                KeyParameterSecure: FaunaDevKey
                Indices:
                    -
                        Name: users_by_sub
                        Terms:
                            -
                                - data
                                - sub
                    -
                        Name: users_by_displayName
                        Terms:
                            -
                                - data
                                - displayName

    Outputs:
        Response:
            Value:
                Fn::GetAtt:
                    - FaunaDB
                    - Response