service: faunadb-custom-resource

plugins:
    - serverless-deployment-bucket

custom:
    stage: ${opt:stage, self:provider.stage}
    key: /fauna/FaunaKey-${self:custom.stage}

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2
    deploymentBucket:
        name: hex-deployment-bucket
        serverSideEncryption: AES256

resources:
    Resources:
        # Our custom resource
        UserCollection:
            Type: Custom::FaunaCollection
            Properties:
                ServiceToken:
                    Fn::ImportValue: fauna-collection-lambda-arn
                CollectionName: users
                KeyParameterSecure: ${self:custom.key}
                Indices:
                    user-id:
                        Name: user_by_sub
                        Terms:
                            - field:
                                  - data
                                  - sub
                        Unique: true
                    user-display:
                        Name: user_by_displayName
                        Terms:
                            - field:
                                  - data
                                  - displayName
                        Unique: true

        CubeCollection:
            Type: Custom::FaunaCollection
            Properties:
                ServiceToken:
                    Fn::ImportValue: fauna-collection-lambda-arn

                CollectionName: cubes
                KeyParameterSecure: ${self:custom.key}
                Indices:
                    owner:
                        Name: cubes_by_owner
                        Terms:
                            - field:
                                  - data
                                  - owner


    Outputs:
        UserResponse:
            Value:
                Fn::GetAtt:
                    - UserCollection
                    - Response

        CubeResponse:
            Value:
                Fn::GetAtt:
                    - CubeCollection
                    - Response