service: faunadb-custom-resource

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2

resources:
    Resources:
        # Our custom resource
        FaunaDB:
            Type: Custom::FaunaClass
            Properties:
                ServiceToken:
                    Fn::ImportValue: fauna-class-lambda-arn
                ClassName: users
                KeyParameter: TestKey
                KeyParameterSecure: false
                Indexes:
                    -
                        Name: users_by_sub
                        Terms:
                            -
                                - data
                                - sub
                    -
                        Name: users_by_displayName
                        Terms:
                            -
                                - data
                                - displayName

    Outputs:
        Class:
            Value:
                Fn::GetAtt:
                    - FaunaDB
                    - ClassName
        Indexes:
            Value:
                Fn::Join:
                    - ', '
                    - Fn::GetAtt:
                        - FaunaDB
                        - Indexes