service: hex-api-endpoints

custom:
    # Our stage is based on what is passed in when running serverless
    # commands. Or falls back to what we have set in the provider section.
    stage: ${opt:stage, self:provider.stage}

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2

resources:
    Resources:
        HexApiGW:
            Type: AWS::ApiGateway::RestApi
            Properties:
                Name: HexApiGW

    Outputs:
        apiGatewayRestApiId:
            Value:
                Ref: HexApiGW
            Export:
                Name: HexApiGateway-restApiId