service: hex-api-base

custom:
    # Our stage is based on what is passed in when running serverless
    # commands. Or falls back to what we have set in the provider section.
    stage: ${opt:stage, self:provider.stage}

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2
    deploymentBucket:
        name: hex-deployment-bucket-${self:custom.stage}
        serverSideEncryption: AES256

    stackTags:
        function: api

resources:
    Description: The Serverless template for deploying the Base API Gateway resource

    Resources:
        HexApiGW:
            Type: AWS::ApiGateway::RestApi
            Properties:
                Name: ${self:custom.stage}-HexApiGW
                Description: API Gateway for Hexahedron.io

    Outputs:
        ApiGatewayRestApiId:
            Value:
                Ref: HexApiGW
            Export:
                Name: ${self:custom.stage}-HexApiGateway-restApiId

        ApiGatewayRestApiRootResourceId:
            Value:
                Fn::GetAtt:
                    - HexApiGW
                    - RootResourceId
            Export:
                Name: ${self:custom.stage}-HexApiGateway-rootResourceId