service: hex-database-users

custom:
    # Stage based on passed param, with fallback
    stage: ${opt:stage, self:provider.stage}

    # Set table name
    tableName: ${self:custom.stage}-users

    # Set DynamoDB throughput
    tableThroughputs:
        prod: 5
        default: 1
    tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2
    deploymentBucket:
        name: hex-deployment-bucket
        serverSideEncryption: AES256

resources:
    Resources:
        UserTable:
            Type: AWS::DynamoDB::Table
            Properties:
                # Generate name based on stage
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: userId
                      AttributeType: S

                KeySchema:
                    - AttributeName: userId
                      KeyType: HASH

                ProvisionedThroughput:
                    ReadCapacityUnits: ${self:custom.tableThroughput}
                    WriteCapacityUnits: ${self:custom.tableThroughput}

    Outputs:
        UserTableArn:
            Value:
                Fn::GetAtt:
                    - UserTable
                    - Arn
            Export:
                Name: ${self:custom.stage}-UserTableArn