service: hex-api-authorizer

plugins:
    - serverless-plugin-common-excludes
    - serverless-plugin-include-dependencies

custom:
    # Our stage is based on what is passed in when running serverless
    # commands. Or falls back to what we have set in the provider section.
    stage: ${opt:stage, self:provider.stage}

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2
    deploymentBucket:
        name: hex-deployment-bucket
        serverSideEncryption: AES256

functions:
    authorizer:
        handler: authorizer.main
        environment:
            Region: ${self:provider.region}
            UserPoolId:
                Fn::ImportValue: ${self:custom.stage}-hex-user-pool-id
            AuthorizerClient:
                Fn::ImportValue: ${self:custom.stage}-hex-authorizer-client-id

resources:
    Outputs:
        AuthorizerFunction:
            Value:
                Fn::GetAtt:
                    - AuthorizerLambdaFunction
                    - Arn
            Export:
                Name: ${self:custom.stage}-authorizer